### ISSUE TITLE
Concerns about this

### ISSUE THREAD

**Issue by ROCKNROLLKID** [Cisco-Talos/BASS#1]
I have some concerns about this tool. usually automatic signatures generate quite a bit of false positives all the time and ClamAV already suffers from a great deal of false positives. Will this be a issue with this tool?

Also, is this going to be like a utterly complicated tool to use, like the bytecode signatures are? Judging by the installation instructions, it already looks like you need to jump through hoops to use it and I don't think a lot of people like t do that.

Lastly, is it going to be GUI based or all command line?

**Comment by vrtadmin** [comment]
This tool is meant for reverse engineers who write ClamAV detection.  It can be complicated to make.

As far as ClamAV "suffering" from a "great deal of false positives", unless those false positives are [submitted to us](http://www.clamav.net/reports/fp), we don't know about them
