### ISSUE TITLE
License for klcs code

### ISSUE THREAD

**Issue by pombredanne** [Cisco-Talos/BASS#2]
Hi:
In searching for a k-lcs implementation I found yours which looks great.
https://github.com/Cisco-Talos/BASS/blob/master/bass/python/src/_lcs.cpp
Could it be something that could be used as a library outside of BASS? and to allow such use would you consider an alternate licensing that would allow to use this with Apache-licensed code?
Thank you for your kind consideration!

**Comment by pombredanne** [comment]
@zaddach ping?

**Comment by pombredanne** [comment]
@Thiefyface @vrtadmin  @xabiugarte may be you can help me there, if anything to get an answer one way or the other?

**Comment by vrtadmin** [comment]
We are unable to alter the license on this project at this time.

**Comment by pombredanne** [comment]
@vrtadmin Thank you! I can take no for an answer.
