### ISSUE TITLE
RED ERROR when launch command line : docker-compose build

### ISSUE THREAD

**Issue by Azaretdodo** [Cisco-Talos/BASS#4]
Hello Dear IT Community worker Talos,

[RED ERROR when DOCKER-BUILD compose.txt](https://github.com/Cisco-Talos/BASS/files/2395881/RED.ERROR.when.DOCKER-BUILD.compose.txt)

I went to back to the BASS directory for launch the command line : docker-compose build …

Finally It answer an error for stop the command line since the file : /tmp/ida-sdk.zip

I attach at this ticket the error which too the number process error,

Thank you in advance to follow my ticket for repair,

Regards.

Dorian ROSSE.

I

**Comment by zaddach** [comment]
Hi Dorian,

this looks like the ida-sdk.zip download doesn't work. First make sure that you exported the IDA_WEB_PASSWORD environment variable, and then make sure that the access to the Hex-Rays protected web area is still working.

If your problem persists, please post the output from `docker-compose build` here, so that we can help you better.

**Comment by Azaretdodo** [comment]
Hello,


How to export your environment variable ?

I don’t known what you expected by Hex-Rays web aera protected ☹

I have to say that I do not launch the command line « docker-compose build » for the first time I have launched a first time but I was forgotten the third add-on for the BASS program ☹ ( the one and the second are very easy than this third add-on)

Yes I have the two errors which the IDA program (but white errors),

how to go out the result of the command line « docker-compose build » please?

Thank you in advance to take the ticket,

Regards.


Dorian ROSSE.

________________________________
De : Jonas Zaddach <notifications@github.com>
Envoyé : Wednesday, September 19, 2018 3:01:10 PM
À : Cisco-Talos/BASS
Cc : Azaretdodo; Author
Objet : Re: [Cisco-Talos/BASS] RED ERROR when launch command line : docker-compose build (#4)


Hi Dorian,

this looks like the ida-sdk.zip download doesn't work. First make sure that you exported the IDA_WEB_PASSWORD environment variable, and then make sure that the access to the Hex-Rays protected web area is still working.

If your problem persists, please post the output from docker-compose build here, so that we can help you better.

**Comment by zaddach** [comment]
I've updated the documentation to reflect this better: https://github.com/Cisco-Talos/BASS/commit/6dd8b7aa4b13ddcd48f0c8fbd64ac43955157420

Please note that the current version only works with IDA Pro 7.0, you'll have problems if you try to use IDA Pro 7.1 due to a change in the installation behavior of IDA. IDA 6.95 is not supported by us any more.

**Comment by Azaretdodo** [comment]
I was download ida 7.0 free but I don’t found the ida pro anything,

Where can I find the pro ida 7.0 ?

Thank you in advance for the doc support but I will wait firstly you answer about ida,

Regards.


Dorian ROSSE.

________________________________
De : Jonas Zaddach <notifications@github.com>
Envoyé : Wednesday, September 19, 2018 6:35:02 PM
À : Cisco-Talos/BASS
Cc : Azaretdodo; Author
Objet : Re: [Cisco-Talos/BASS] RED ERROR when launch command line : docker-compose build (#4)


I've updated the documentation to reflect this better: 6dd8b7a<https://github.com/Cisco-Talos/BASS/commit/6dd8b7aa4b13ddcd48f0c8fbd64ac43955157420>

Please note that the current version only works with IDA Pro 7.0, you'll have problems if you try to use IDA Pro 7.1 due to a change in the installation behavior of IDA. IDA 6.95 is not supported by us any more.

**Comment by Azaretdodo** [comment]
Hello,


I went to set up a password for ida but now I have this new RED ERROR :

chmod: cannot access '/installation/ida.run': No such file or directory

I was run this command line but which a password :

sudo docker build -t ida --build-arg IDA_PASSWORD=<password> docker-ida/ida

How to repair this error ? 😃

Thank you in advance to answer this new problem,

Regards.


Dorian ROSSE.

________________________________
De : Jonas Zaddach <notifications@github.com>
Envoyé : Wednesday, September 19, 2018 6:35:02 PM
À : Cisco-Talos/BASS
Cc : Azaretdodo; Author
Objet : Re: [Cisco-Talos/BASS] RED ERROR when launch command line : docker-compose build (#4)


I've updated the documentation to reflect this better: 6dd8b7a<https://github.com/Cisco-Talos/BASS/commit/6dd8b7aa4b13ddcd48f0c8fbd64ac43955157420>

Please note that the current version only works with IDA Pro 7.0, you'll have problems if you try to use IDA Pro 7.1 due to a change in the installation behavior of IDA. IDA 6.95 is not supported by us any more.

**Comment by Azaretdodo** [comment]
Hello,


Do you work on my Server today ?

Because I Watch some GitHub repository didn't installed on my own server and I want to take again the BASS install 😄

Thank you in advance to answer if I can be able to update my server because It is forbidden to update the server 🙁

Regards.


Dorian ROSSE.
________________________________
De : Jonas Zaddach <notifications@github.com>
Envoyé : mercredi 19 septembre 2018 18:35
À : Cisco-Talos/BASS
Cc : Azaretdodo; Author
Objet : Re: [Cisco-Talos/BASS] RED ERROR when launch command line : docker-compose build (#4)


I've updated the documentation to reflect this better: 6dd8b7a<https://github.com/Cisco-Talos/BASS/commit/6dd8b7aa4b13ddcd48f0c8fbd64ac43955157420>

Please note that the current version only works with IDA Pro 7.0, you'll have problems if you try to use IDA Pro 7.1 due to a change in the installation behavior of IDA. IDA 6.95 is not supported by us any more.

**Comment by Azaretdodo** [comment]
Hello,


today Eleven october two thousant eighteen I am forbidden to log in my computer where I installed BASS also are you logged to my computer ?

Than you in advance to answer my ask,

Regards.


Dorian ROSSE.

________________________________
De : Dorian ROSSE <dorianbrice@hotmail.fr>
Envoyé : Thursday, September 27, 2018 11:15:27 AM
À : Cisco-Talos/BASS
Objet : RE: [Cisco-Talos/BASS] RED ERROR when launch command line : docker-compose build (#4)

Hello,


Do you work on my Server today ?

Because I Watch some GitHub repository didn't installed on my own server and I want to take again the BASS install 😄

Thank you in advance to answer if I can be able to update my server because It is forbidden to update the server 🙁

Regards.


Dorian ROSSE.
________________________________
De : Jonas Zaddach <notifications@github.com>
Envoyé : mercredi 19 septembre 2018 18:35
À : Cisco-Talos/BASS
Cc : Azaretdodo; Author
Objet : Re: [Cisco-Talos/BASS] RED ERROR when launch command line : docker-compose build (#4)


I've updated the documentation to reflect this better: 6dd8b7a<https://github.com/Cisco-Talos/BASS/commit/6dd8b7aa4b13ddcd48f0c8fbd64ac43955157420>

Please note that the current version only works with IDA Pro 7.0, you'll have problems if you try to use IDA Pro 7.1 due to a change in the installation behavior of IDA. IDA 6.95 is not supported by us any more.

**Comment by Azaretdodo** [comment]
Hello,


I went to return to my setup,

The BASS installing finish at **step 14/55 : RUN unzip /tmp/ida-sdk.zip**

I launch the advicing command line Following : **tail -f $( ls /tmp/bass_logs/*.log | tail -n 1 )**

Now I Don't know how to install the BASS Framework and I will be happy if you come to my ticket Failure,

Regards.


Dorian ROSSE.
