### ISSUE TITLE
Hilarious problem which IDA Pro

### ISSUE THREAD

**Issue by Azaretdodo** [Cisco-Talos/BASS#6]
Hello…

Where can I find IDA Pro for free ???

You are hilarious you put a GitHub repository which a third-type program costing 2000 euros ><

If you know where I can have this program for free your repository aren't hilarious ;)

Thank you too in advance to answer the ticket before this ticket :)

regards.

Dorian ROSSE.

**Comment by finchy** [comment]
You can use a trial version of IDA for free from their site. This additional tool we’ve written is for users of IDA. It’s not for everyone, and requires advanced knowledge of reverse engineering to use.

**Comment by Azaretdodo** [comment]
There is more easy :

1) => download IDA 7.0 Freeware dot run
2) add execute right to the user right
3) launch the program !

DO IDA 7.0 Freeware can works what IDA Pro should done on the BASS Framework ?

Thank you in advance to answer if IDA Freeware is better :)

Regards.


Dorian ROSSE.

**Comment by Azaretdodo** [comment]
why a trial version when a free version do the same and maybe less but for free ???
